#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# My aliases

alias pyvenv-play='. ~/Coding/pyvenvs/play/bin/activate'
alias ipynote='cd ~/Coding/ipynotes/ && ipython notebook'
alias ipy-spark='IPYTHON=1 pyspark'
alias ipynote-spark='cd ~/Coding/ipynotes/ && IPYTHON_OPTS=notebook pyspark'
alias reset-tunnel='sudo ipfw -q -f flush'

ssh-tunnel() {
    sshuttle --dns -r rafaelbarreto@"$1" 0/0
}

# My exports

export JAVA_HOME=`/usr/libexec/java_home`
# to avoid GitHub throttling in homebrew
export HOMEBREW_GITHUB_API_TOKEN=
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
# AWS credentials
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=

# My bindings

# enable backwards incremental search using Ctrl-r 
bindkey "^R" history-incremental-search-backward

pick_tmux_session
